# TypeProf 0.21.3

# Classes
module SDLRuby
  module SDL
    SDL_DESTROY_RENDERER: Integer
    SDL_DESTROY_TEXTURE: Integer
    SDL_FREE: Integer
    SDL_FREE_CURSOR: Integer
    SDL_FREE_FORMAT: Integer
    SDL_FREE_PALETTE: Integer
    SDL_FREE_RW: Integer
    SDL_FREE_SURFACE: Integer
    AUDIO_U8: Integer
    AUDIO_S8: Integer
    AUDIO_U16LSB: Integer
    AUDIO_S16LSB: Integer
    AUDIO_U16MSB: Integer
    AUDIO_S16MSB: Integer
    AUDIO_U16: Integer
    AUDIO_S16: Integer
    AUDIO_S32LSB: Integer
    AUDIO_S32MSB: Integer
    AUDIO_S32: Integer
    AUDIO_F32LSB: Integer
    AUDIO_F32MSB: Integer
    AUDIO_F32: Integer
    AUDIO_U16SYS: Integer
    AUDIO_S16SYS: Integer
    AUDIO_S32SYS: Integer
    AUDIO_F32SYS: Integer
    SDL_AUDIO_ALLOW_FREQUENCY_CHANGE: Integer
    SDL_AUDIO_ALLOW_FORMAT_CHANGE: Integer
    SDL_AUDIO_ALLOW_CHANNELS_CHANGE: Integer
    SDL_AUDIO_ALLOW_SAMPLES_CHANGE: Integer
    SDL_AUDIO_ALLOW_ANY_CHANGE: Integer
    SDL_AudioSpec: Class
    SDL_AUDIO_STOPPED: Integer
    SDL_AUDIO_PLAYING: Integer
    SDL_AUDIO_PAUSED: Integer
    SDL_MIX_MAXVOLUME: Integer
    SDL_BLENDMODE_NONE: Integer
    SDL_BLENDMODE_BLEND: Integer
    SDL_BLENDMODE_ADD: Integer
    SDL_BLENDMODE_MOD: Integer
    SDL_BLENDMODE_MUL: Integer
    SDL_BLENDMODE_INVALID: Integer
    SDL_Keysym: Class
    SDL_RELEASED: Integer
    SDL_PRESSED: Integer
    SDL_FIRSTEVENT: Integer
    SDL_QUIT: Integer
    SDL_APP_TERMINATING: Integer
    SDL_APP_LOWMEMORY: Integer
    SDL_APP_WILLENTERBACKGROUND: Integer
    SDL_APP_DIDENTERBACKGROUND: Integer
    SDL_APP_WILLENTERFOREGROUND: Integer
    SDL_APP_DIDENTERFOREGROUND: Integer
    SDL_LOCALECHANGED: Integer
    SDL_DISPLAYEVENT: Integer
    SDL_WINDOWEVENT: Integer
    SDL_SYSWMEVENT: Integer
    SDL_KEYDOWN: Integer
    SDL_KEYUP: Integer
    SDL_TEXTEDITING: Integer
    SDL_TEXTINPUT: Integer
    SDL_KEYMAPCHANGED: Integer
    SDL_TEXTEDITING_EXT: Integer
    SDL_MOUSEMOTION: Integer
    SDL_MOUSEBUTTONDOWN: Integer
    SDL_MOUSEBUTTONUP: Integer
    SDL_MOUSEWHEEL: Integer
    SDL_JOYAXISMOTION: Integer
    SDL_JOYBALLMOTION: Integer
    SDL_JOYHATMOTION: Integer
    SDL_JOYBUTTONDOWN: Integer
    SDL_JOYBUTTONUP: Integer
    SDL_JOYDEVICEADDED: Integer
    SDL_JOYDEVICEREMOVED: Integer
    SDL_JOYBATTERYUPDATED: Integer
    SDL_CONTROLLERAXISMOTION: Integer
    SDL_CONTROLLERBUTTONDOWN: Integer
    SDL_CONTROLLERBUTTONUP: Integer
    SDL_CONTROLLERDEVICEADDED: Integer
    SDL_CONTROLLERDEVICEREMOVED: Integer
    SDL_CONTROLLERDEVICEREMAPPED: Integer
    SDL_CONTROLLERTOUCHPADDOWN: Integer
    SDL_CONTROLLERTOUCHPADMOTION: Integer
    SDL_CONTROLLERTOUCHPADUP: Integer
    SDL_CONTROLLERSENSORUPDATE: Integer
    SDL_FINGERDOWN: Integer
    SDL_FINGERUP: Integer
    SDL_FINGERMOTION: Integer
    SDL_DOLLARGESTURE: Integer
    SDL_DOLLARRECORD: Integer
    SDL_MULTIGESTURE: Integer
    SDL_CLIPBOARDUPDATE: Integer
    SDL_DROPFILE: Integer
    SDL_DROPTEXT: Integer
    SDL_DROPBEGIN: Integer
    SDL_DROPCOMPLETE: Integer
    SDL_AUDIODEVICEADDED: Integer
    SDL_AUDIODEVICEREMOVED: Integer
    SDL_SENSORUPDATE: Integer
    SDL_RENDER_TARGETS_RESET: Integer
    SDL_RENDER_DEVICE_RESET: Integer
    SDL_POLLSENTINEL: Integer
    SDL_USEREVENT: Integer
    SDL_LASTEVENT: Integer
    SDL_CommonEvent: Class
    SDL_DisplayEvent: Class
    SDL_WindowEvent: Class
    SDL_KeyboardEvent: Class
    SDL_TEXTEDITINGEVENT_TEXT_SIZE: Integer
    SDL_TextEditingEvent: Class
    SDL_TextEditingExtEvent: Class
    SDL_TEXTINPUTEVENT_TEXT_SIZE: Integer
    SDL_TextInputEvent: Class
    SDL_MouseMotionEvent: Class
    SDL_MouseButtonEvent: Class
    SDL_MouseWheelEvent: Class
    SDL_JoyAxisEvent: Class
    SDL_JoyBallEvent: Class
    SDL_JoyHatEvent: Class
    SDL_JoyButtonEvent: Class
    SDL_JoyDeviceEvent: Class
    SDL_JoyBatteryEvent: Class
    SDL_ControllerAxisEvent: Class
    SDL_ControllerButtonEvent: Class
    SDL_ControllerDeviceEvent: Class
    SDL_ControllerTouchpadEvent: Class
    SDL_ControllerSensorEvent: Class
    SDL_AudioDeviceEvent: Class
    SDL_TouchFingerEvent: Class
    SDL_MultiGestureEvent: Class
    SDL_DollarGestureEvent: Class
    SDL_DropEvent: Class
    SDL_SensorEvent: Class
    SDL_QuitEvent: Class
    SDL_OSEvent: Class
    SDL_UserEvent: Class
    SDL_SysWMEvent: Class
    SDL_Event: Class
    SDL_ADDEVENT: Integer
    SDL_PEEKEVENT: Integer
    SDL_GETEVENT: Integer
    SDL_HINT_DEFAULT: Integer
    SDL_HINT_NORMAL: Integer
    SDL_HINT_OVERRIDE: Integer
    SDL_Locale: Class
    SDL_MESSAGEBOX_ERROR: Integer
    SDL_MESSAGEBOX_WARNING: Integer
    SDL_MESSAGEBOX_INFORMATION: Integer
    SDL_SYSTEM_CURSOR_ARROW: Integer
    SDL_SYSTEM_CURSOR_IBEAM: Integer
    SDL_SYSTEM_CURSOR_WAIT: Integer
    SDL_SYSTEM_CURSOR_CROSSHAIR: Integer
    SDL_SYSTEM_CURSOR_WAITARROW: Integer
    SDL_SYSTEM_CURSOR_SIZENWSE: Integer
    SDL_SYSTEM_CURSOR_SIZENESW: Integer
    SDL_SYSTEM_CURSOR_SIZEWE: Integer
    SDL_SYSTEM_CURSOR_SIZENS: Integer
    SDL_SYSTEM_CURSOR_SIZEALL: Integer
    SDL_SYSTEM_CURSOR_NO: Integer
    SDL_SYSTEM_CURSOR_HAND: Integer
    SDL_NUM_SYSTEM_CURSORS: Integer
    SDL_MOUSEWHEEL_NORMAL: Integer
    SDL_MOUSEWHEEL_FLIPPED: Integer
    SDL_BUTTON: ^(Integer) -> Integer
    SDL_BUTTON_LEFT: Integer
    SDL_BUTTON_MIDDLE: Integer
    SDL_BUTTON_RIGHT: Integer
    SDL_BUTTON_X1: Integer
    SDL_BUTTON_X2: Integer
    SDL_BUTTON_LMASK: Integer
    SDL_BUTTON_MMASK: Integer
    SDL_BUTTON_RMASK: Integer
    SDL_BUTTON_X1MASK: Integer
    SDL_BUTTON_X2MASK: Integer
    SDL_Palette: Class
    SDL_ALPHA_OPAQUE: Integer
    SDL_ALPHA_TRANSPARENT: Integer
    SDL_Color: Class
    SDL_PIXELFORMAT_UNKNOWN: Integer
    SDL_PIXELFORMAT_INDEX1LSB: Integer
    SDL_PIXELFORMAT_INDEX1MSB: Integer
    SDL_PIXELFORMAT_INDEX4LSB: Integer
    SDL_PIXELFORMAT_INDEX4MSB: Integer
    SDL_PIXELFORMAT_INDEX8: Integer
    SDL_PIXELFORMAT_RGB332: Integer
    SDL_PIXELFORMAT_XRGB4444: Integer
    SDL_PIXELFORMAT_RGB444: Integer
    SDL_PIXELFORMAT_XBGR4444: Integer
    SDL_PIXELFORMAT_BGR444: Integer
    SDL_PIXELFORMAT_XRGB1555: Integer
    SDL_PIXELFORMAT_RGB555: Integer
    SDL_PIXELFORMAT_XBGR1555: Integer
    SDL_PIXELFORMAT_BGR555: Integer
    SDL_PIXELFORMAT_ARGB4444: Integer
    SDL_PIXELFORMAT_RGBA4444: Integer
    SDL_PIXELFORMAT_ABGR4444: Integer
    SDL_PIXELFORMAT_BGRA4444: Integer
    SDL_PIXELFORMAT_ARGB1555: Integer
    SDL_PIXELFORMAT_RGBA5551: Integer
    SDL_PIXELFORMAT_ABGR1555: Integer
    SDL_PIXELFORMAT_BGRA5551: Integer
    SDL_PIXELFORMAT_RGB565: Integer
    SDL_PIXELFORMAT_BGR565: Integer
    SDL_PIXELFORMAT_RGB24: Integer
    SDL_PIXELFORMAT_BGR24: Integer
    SDL_PIXELFORMAT_XRGB8888: Integer
    SDL_PIXELFORMAT_RGB888: Integer
    SDL_PIXELFORMAT_RGBX8888: Integer
    SDL_PIXELFORMAT_XBGR8888: Integer
    SDL_PIXELFORMAT_BGR888: Integer
    SDL_PIXELFORMAT_BGRX8888: Integer
    SDL_PIXELFORMAT_ARGB8888: Integer
    SDL_PIXELFORMAT_RGBA8888: Integer
    SDL_PIXELFORMAT_ABGR8888: Integer
    SDL_PIXELFORMAT_BGRA8888: Integer
    SDL_PIXELFORMAT_ARGB2101010: Integer
    SDL_PIXELFORMAT_RGBA32: Integer
    SDL_PIXELFORMAT_ARGB32: Integer
    SDL_PIXELFORMAT_BGRA32: Integer
    SDL_PIXELFORMAT_ABGR32: Integer
    SDL_PIXELFORMAT_YV12: Integer
    SDL_PIXELFORMAT_IYUV: Integer
    SDL_PIXELFORMAT_YUY2: Integer
    SDL_PIXELFORMAT_UYVY: Integer
    SDL_PIXELFORMAT_YVYU: Integer
    SDL_PIXELFORMAT_NV12: Integer
    SDL_PIXELFORMAT_NV21: Integer
    SDL_PIXELFORMAT_EXTERNAL_OES: Integer
    SDL_PixelFormat: Class
    SDL_Point: Class
    SDL_FPoint: Class
    SDL_Rect: Class
    SDL_FRect: Class
    SDL_RENDERER_SOFTWARE: Integer
    SDL_RENDERER_ACCELERATED: Integer
    SDL_RENDERER_PRESENTVSYNC: Integer
    SDL_RENDERER_TARGETTEXTURE: Integer
    SDL_RendererInfo: Class
    SDL_FLIP_NONE: Integer
    SDL_FLIP_HORIZONTAL: Integer
    SDL_FLIP_VERTICAL: Integer
    SDL_SCALEMODE_NEAREST: Integer
    SDL_SCALEMODE_LINEAR: Integer
    SDL_SCALEMODE_BEST: Integer
    SDL_TEXTUREACCESS_STATIC: Integer
    SDL_TEXTUREACCESS_STREAMING: Integer
    SDL_TEXTUREACCESS_TARGET: Integer
    SDL_RWOPS_UNKNOWN: Integer
    SDL_RWOPS_WINFILE: Integer
    SDL_RWOPS_STDFILE: Integer
    SDL_RWOPS_JNIFILE: Integer
    SDL_RWOPS_MEMORY: Integer
    SDL_RWOPS_MEMORY_RO: Integer
    SDL_SCANCODE_UNKNOWN: Integer
    SDL_SCANCODE_A: Integer
    SDL_SCANCODE_B: Integer
    SDL_SCANCODE_C: Integer
    SDL_SCANCODE_D: Integer
    SDL_SCANCODE_E: Integer
    SDL_SCANCODE_F: Integer
    SDL_SCANCODE_G: Integer
    SDL_SCANCODE_H: Integer
    SDL_SCANCODE_I: Integer
    SDL_SCANCODE_J: Integer
    SDL_SCANCODE_K: Integer
    SDL_SCANCODE_L: Integer
    SDL_SCANCODE_M: Integer
    SDL_SCANCODE_N: Integer
    SDL_SCANCODE_O: Integer
    SDL_SCANCODE_P: Integer
    SDL_SCANCODE_Q: Integer
    SDL_SCANCODE_R: Integer
    SDL_SCANCODE_S: Integer
    SDL_SCANCODE_T: Integer
    SDL_SCANCODE_U: Integer
    SDL_SCANCODE_V: Integer
    SDL_SCANCODE_W: Integer
    SDL_SCANCODE_X: Integer
    SDL_SCANCODE_Y: Integer
    SDL_SCANCODE_Z: Integer
    SDL_SCANCODE_1: Integer
    SDL_SCANCODE_2: Integer
    SDL_SCANCODE_3: Integer
    SDL_SCANCODE_4: Integer
    SDL_SCANCODE_5: Integer
    SDL_SCANCODE_6: Integer
    SDL_SCANCODE_7: Integer
    SDL_SCANCODE_8: Integer
    SDL_SCANCODE_9: Integer
    SDL_SCANCODE_0: Integer
    SDL_SCANCODE_RETURN: Integer
    SDL_SCANCODE_ESCAPE: Integer
    SDL_SCANCODE_BACKSPACE: Integer
    SDL_SCANCODE_TAB: Integer
    SDL_SCANCODE_SPACE: Integer
    SDL_SCANCODE_MINUS: Integer
    SDL_SCANCODE_EQUALS: Integer
    SDL_SCANCODE_LEFTBRACKET: Integer
    SDL_SCANCODE_RIGHTBRACKET: Integer
    SDL_SCANCODE_BACKSLASH: Integer
    SDL_SCANCODE_NONUSHASH: Integer
    SDL_SCANCODE_SEMICOLON: Integer
    SDL_SCANCODE_APOSTROPHE: Integer
    SDL_SCANCODE_GRAVE: Integer
    SDL_SCANCODE_COMMA: Integer
    SDL_SCANCODE_PERIOD: Integer
    SDL_SCANCODE_SLASH: Integer
    SDL_SCANCODE_CAPSLOCK: Integer
    SDL_SCANCODE_F1: Integer
    SDL_SCANCODE_F2: Integer
    SDL_SCANCODE_F3: Integer
    SDL_SCANCODE_F4: Integer
    SDL_SCANCODE_F5: Integer
    SDL_SCANCODE_F6: Integer
    SDL_SCANCODE_F7: Integer
    SDL_SCANCODE_F8: Integer
    SDL_SCANCODE_F9: Integer
    SDL_SCANCODE_F10: Integer
    SDL_SCANCODE_F11: Integer
    SDL_SCANCODE_F12: Integer
    SDL_SCANCODE_PRINTSCREEN: Integer
    SDL_SCANCODE_SCROLLLOCK: Integer
    SDL_SCANCODE_PAUSE: Integer
    SDL_SCANCODE_INSERT: Integer
    SDL_SCANCODE_HOME: Integer
    SDL_SCANCODE_PAGEUP: Integer
    SDL_SCANCODE_DELETE: Integer
    SDL_SCANCODE_END: Integer
    SDL_SCANCODE_PAGEDOWN: Integer
    SDL_SCANCODE_RIGHT: Integer
    SDL_SCANCODE_LEFT: Integer
    SDL_SCANCODE_DOWN: Integer
    SDL_SCANCODE_UP: Integer
    SDL_SCANCODE_NUMLOCKCLEAR: Integer
    SDL_SCANCODE_KP_DIVIDE: Integer
    SDL_SCANCODE_KP_MULTIPLY: Integer
    SDL_SCANCODE_KP_MINUS: Integer
    SDL_SCANCODE_KP_PLUS: Integer
    SDL_SCANCODE_KP_ENTER: Integer
    SDL_SCANCODE_KP_1: Integer
    SDL_SCANCODE_KP_2: Integer
    SDL_SCANCODE_KP_3: Integer
    SDL_SCANCODE_KP_4: Integer
    SDL_SCANCODE_KP_5: Integer
    SDL_SCANCODE_KP_6: Integer
    SDL_SCANCODE_KP_7: Integer
    SDL_SCANCODE_KP_8: Integer
    SDL_SCANCODE_KP_9: Integer
    SDL_SCANCODE_KP_0: Integer
    SDL_SCANCODE_KP_PERIOD: Integer
    SDL_SCANCODE_NONUSBACKSLASH: Integer
    SDL_SCANCODE_APPLICATION: Integer
    SDL_SCANCODE_POWER: Integer
    SDL_SCANCODE_KP_EQUALS: Integer
    SDL_SCANCODE_F13: Integer
    SDL_SCANCODE_F14: Integer
    SDL_SCANCODE_F15: Integer
    SDL_SCANCODE_F16: Integer
    SDL_SCANCODE_F17: Integer
    SDL_SCANCODE_F18: Integer
    SDL_SCANCODE_F19: Integer
    SDL_SCANCODE_F20: Integer
    SDL_SCANCODE_F21: Integer
    SDL_SCANCODE_F22: Integer
    SDL_SCANCODE_F23: Integer
    SDL_SCANCODE_F24: Integer
    SDL_SCANCODE_EXECUTE: Integer
    SDL_SCANCODE_HELP: Integer
    SDL_SCANCODE_MENU: Integer
    SDL_SCANCODE_SELECT: Integer
    SDL_SCANCODE_STOP: Integer
    SDL_SCANCODE_AGAIN: Integer
    SDL_SCANCODE_UNDO: Integer
    SDL_SCANCODE_CUT: Integer
    SDL_SCANCODE_COPY: Integer
    SDL_SCANCODE_PASTE: Integer
    SDL_SCANCODE_FIND: Integer
    SDL_SCANCODE_MUTE: Integer
    SDL_SCANCODE_VOLUMEUP: Integer
    SDL_SCANCODE_VOLUMEDOWN: Integer
    SDL_SCANCODE_LOCKINGCAPSLOCK: Integer
    SDL_SCANCODE_LOCKINGNUMLOCK: Integer
    SDL_SCANCODE_LOCKINGSCROLLLOCK: Integer
    SDL_SCANCODE_KP_COMMA: Integer
    SDL_SCANCODE_KP_EQUALSAS400: Integer
    SDL_SCANCODE_INTERNATIONAL1: Integer
    SDL_SCANCODE_INTERNATIONAL2: Integer
    SDL_SCANCODE_INTERNATIONAL3: Integer
    SDL_SCANCODE_INTERNATIONAL4: Integer
    SDL_SCANCODE_INTERNATIONAL5: Integer
    SDL_SCANCODE_INTERNATIONAL6: Integer
    SDL_SCANCODE_INTERNATIONAL7: Integer
    SDL_SCANCODE_INTERNATIONAL8: Integer
    SDL_SCANCODE_INTERNATIONAL9: Integer
    SDL_SCANCODE_LANG1: Integer
    SDL_SCANCODE_LANG2: Integer
    SDL_SCANCODE_LANG3: Integer
    SDL_SCANCODE_LANG4: Integer
    SDL_SCANCODE_LANG5: Integer
    SDL_SCANCODE_LANG6: Integer
    SDL_SCANCODE_LANG7: Integer
    SDL_SCANCODE_LANG8: Integer
    SDL_SCANCODE_LANG9: Integer
    SDL_SCANCODE_ALTERASE: Integer
    SDL_SCANCODE_SYSREQ: Integer
    SDL_SCANCODE_CANCEL: Integer
    SDL_SCANCODE_CLEAR: Integer
    SDL_SCANCODE_PRIOR: Integer
    SDL_SCANCODE_RETURN2: Integer
    SDL_SCANCODE_SEPARATOR: Integer
    SDL_SCANCODE_OUT: Integer
    SDL_SCANCODE_OPER: Integer
    SDL_SCANCODE_CLEARAGAIN: Integer
    SDL_SCANCODE_CRSEL: Integer
    SDL_SCANCODE_EXSEL: Integer
    SDL_SCANCODE_KP_00: Integer
    SDL_SCANCODE_KP_000: Integer
    SDL_SCANCODE_THOUSANDSSEPARATOR: Integer
    SDL_SCANCODE_DECIMALSEPARATOR: Integer
    SDL_SCANCODE_CURRENCYUNIT: Integer
    SDL_SCANCODE_CURRENCYSUBUNIT: Integer
    SDL_SCANCODE_KP_LEFTPAREN: Integer
    SDL_SCANCODE_KP_RIGHTPAREN: Integer
    SDL_SCANCODE_KP_LEFTBRACE: Integer
    SDL_SCANCODE_KP_RIGHTBRACE: Integer
    SDL_SCANCODE_KP_TAB: Integer
    SDL_SCANCODE_KP_BACKSPACE: Integer
    SDL_SCANCODE_KP_A: Integer
    SDL_SCANCODE_KP_B: Integer
    SDL_SCANCODE_KP_C: Integer
    SDL_SCANCODE_KP_D: Integer
    SDL_SCANCODE_KP_E: Integer
    SDL_SCANCODE_KP_F: Integer
    SDL_SCANCODE_KP_XOR: Integer
    SDL_SCANCODE_KP_POWER: Integer
    SDL_SCANCODE_KP_PERCENT: Integer
    SDL_SCANCODE_KP_LESS: Integer
    SDL_SCANCODE_KP_GREATER: Integer
    SDL_SCANCODE_KP_AMPERSAND: Integer
    SDL_SCANCODE_KP_DBLAMPERSAND: Integer
    SDL_SCANCODE_KP_VERTICALBAR: Integer
    SDL_SCANCODE_KP_DBLVERTICALBAR: Integer
    SDL_SCANCODE_KP_COLON: Integer
    SDL_SCANCODE_KP_HASH: Integer
    SDL_SCANCODE_KP_SPACE: Integer
    SDL_SCANCODE_KP_AT: Integer
    SDL_SCANCODE_KP_EXCLAM: Integer
    SDL_SCANCODE_KP_MEMSTORE: Integer
    SDL_SCANCODE_KP_MEMRECALL: Integer
    SDL_SCANCODE_KP_MEMCLEAR: Integer
    SDL_SCANCODE_KP_MEMADD: Integer
    SDL_SCANCODE_KP_MEMSUBTRACT: Integer
    SDL_SCANCODE_KP_MEMMULTIPLY: Integer
    SDL_SCANCODE_KP_MEMDIVIDE: Integer
    SDL_SCANCODE_KP_PLUSMINUS: Integer
    SDL_SCANCODE_KP_CLEAR: Integer
    SDL_SCANCODE_KP_CLEARENTRY: Integer
    SDL_SCANCODE_KP_BINARY: Integer
    SDL_SCANCODE_KP_OCTAL: Integer
    SDL_SCANCODE_KP_DECIMAL: Integer
    SDL_SCANCODE_KP_HEXADECIMAL: Integer
    SDL_SCANCODE_LCTRL: Integer
    SDL_SCANCODE_LSHIFT: Integer
    SDL_SCANCODE_LALT: Integer
    SDL_SCANCODE_LGUI: Integer
    SDL_SCANCODE_RCTRL: Integer
    SDL_SCANCODE_RSHIFT: Integer
    SDL_SCANCODE_RALT: Integer
    SDL_SCANCODE_RGUI: Integer
    SDL_SCANCODE_MODE: Integer
    SDL_SCANCODE_AUDIONEXT: Integer
    SDL_SCANCODE_AUDIOPREV: Integer
    SDL_SCANCODE_AUDIOSTOP: Integer
    SDL_SCANCODE_AUDIOPLAY: Integer
    SDL_SCANCODE_AUDIOMUTE: Integer
    SDL_SCANCODE_MEDIASELECT: Integer
    SDL_SCANCODE_WWW: Integer
    SDL_SCANCODE_MAIL: Integer
    SDL_SCANCODE_CALCULATOR: Integer
    SDL_SCANCODE_COMPUTER: Integer
    SDL_SCANCODE_AC_SEARCH: Integer
    SDL_SCANCODE_AC_HOME: Integer
    SDL_SCANCODE_AC_BACK: Integer
    SDL_SCANCODE_AC_FORWARD: Integer
    SDL_SCANCODE_AC_STOP: Integer
    SDL_SCANCODE_AC_REFRESH: Integer
    SDL_SCANCODE_AC_BOOKMARKS: Integer
    SDL_SCANCODE_BRIGHTNESSDOWN: Integer
    SDL_SCANCODE_BRIGHTNESSUP: Integer
    SDL_SCANCODE_DISPLAYSWITCH: Integer
    SDL_SCANCODE_KBDILLUMTOGGLE: Integer
    SDL_SCANCODE_KBDILLUMDOWN: Integer
    SDL_SCANCODE_KBDILLUMUP: Integer
    SDL_SCANCODE_EJECT: Integer
    SDL_SCANCODE_SLEEP: Integer
    SDL_SCANCODE_APP1: Integer
    SDL_SCANCODE_APP2: Integer
    SDL_SCANCODE_AUDIOREWIND: Integer
    SDL_SCANCODE_AUDIOFASTFORWARD: Integer
    SDL_SCANCODE_SOFTLEFT: Integer
    SDL_SCANCODE_SOFTRIGHT: Integer
    SDL_SCANCODE_CALL: Integer
    SDL_SCANCODE_ENDCALL: Integer
    SDL_NUM_SCANCODES: Integer
    SDL_DONTFREE: Integer
    SDL_Surface: Class
    SDL_version: Class
    SDL_WINDOW_FULLSCREEN: Integer
    SDL_WINDOW_OPENGL: Integer
    SDL_WINDOW_SHOWN: Integer
    SDL_WINDOW_HIDDEN: Integer
    SDL_WINDOW_BORDERLESS: Integer
    SDL_WINDOW_RESIZABLE: Integer
    SDL_WINDOW_MINIMIZED: Integer
    SDL_WINDOW_MAXIMIZED: Integer
    SDL_WINDOW_MOUSE_GRABBED: Integer
    SDL_WINDOW_INPUT_FOCUS: Integer
    SDL_WINDOW_MOUSE_FOCUS: Integer
    SDL_WINDOW_FULLSCREEN_DESKTOP: Integer
    SDL_WINDOW_FOREIGN: Integer
    SDL_WINDOW_ALLOW_HIGHDPI: Integer
    SDL_WINDOW_MOUSE_CAPTURE: Integer
    SDL_WINDOW_ALWAYS_ON_TOP: Integer
    SDL_WINDOW_SKIP_TASKBAR: Integer
    SDL_WINDOW_UTILITY: Integer
    SDL_WINDOW_TOOLTIP: Integer
    SDL_WINDOW_POPUP_MENU: Integer
    SDL_WINDOW_KEYBOARD_GRABBED: Integer
    SDL_WINDOW_VULKAN: Integer
    SDL_WINDOW_METAL: Integer
    SDL_WINDOW_INPUT_GRABBED: Integer
    SDL_WINDOWPOS_UNDEFINED: Integer
    SDL_WINDOWPOS_CENTERED: Integer
    SDL_HITTEST_NORMAL: Integer
    SDL_HITTEST_DRAGGABLE: Integer
    SDL_HITTEST_RESIZE_TOPLEFT: Integer
    SDL_HITTEST_RESIZE_TOP: Integer
    SDL_HITTEST_RESIZE_TOPRIGHT: Integer
    SDL_HITTEST_RESIZE_RIGHT: Integer
    SDL_HITTEST_RESIZE_BOTTOMRIGHT: Integer
    SDL_HITTEST_RESIZE_BOTTOM: Integer
    SDL_HITTEST_RESIZE_BOTTOMLEFT: Integer
    SDL_HITTEST_RESIZE_LEFT: Integer
    SDL_ORIENTATION_UNKNOWN: Integer
    SDL_ORIENTATION_LANDSCAPE: Integer
    SDL_ORIENTATION_LANDSCAPE_FLIPPED: Integer
    SDL_ORIENTATION_PORTRAIT: Integer
    SDL_ORIENTATION_PORTRAIT_FLIPPED: Integer
    SDL_FLASH_CANCEL: Integer
    SDL_FLASH_BRIEFLY: Integer
    SDL_FLASH_UNTIL_FOCUSED: Integer
    SDL_DisplayMode: Class
    SDL_NONSHAPEABLE_WINDOW: Integer
    SDL_INVALID_SHAPE_ARGUMENT: Integer
    SDL_WINDOW_LACKS_SHAPE: Integer
    ShapeModeDefault: Integer
    ShapeModeBinarizeAlpha: Integer
    ShapeModeReverseBinarizeAlpha: Integer
    ShapeModeColorKey: Integer
    SDL_SHAPEMODEALPHA: ^(untyped) -> untyped
    SDL_WindowShapeParams: Class
    SDL_WindowShapeMode: Class
    SDL_INIT_TIMER: Integer
    SDL_INIT_AUDIO: Integer
    SDL_INIT_VIDEO: Integer
    SDL_INIT_JOYSTICK: Integer
    SDL_INIT_HAPTIC: Integer
    SDL_INIT_GAMEPAD: Integer
    SDL_INIT_EVENTS: Integer
    SDL_INIT_SENSOR: Integer
    SDL_INIT_EVERYTHING: Integer

    def self.tmp_value: (*String) -> Array[untyped]?
    def self.init: (?nil) -> void
    def self.init?: (untyped) -> boolish
    def self.quit: -> void
    def self.clipboard_text: -> String
    def self.clipboard_text?: -> bool
    def self.clipboard_text=: (String) -> void
    def self.cpu_cache_line_size: -> Integer
    def self.cpu_count: -> Integer
    def self.system_ram: -> Integer
    def self.last_error_message: -> String
    def self.last_error_message=: (String) -> void
    def self.base_path: -> String
    def self.locales: -> Array[Array[String]]?
    def self.alert: (String, ?String?, ?flags: Integer?, ?window: nil) -> void
    def self.error_alert: (String, ?String) -> void
    def self.warn_alert: (String, ?String) -> void
    def self.info_alert: (String, ?String) -> void
    def self.open_url: (String) -> void
    def self.platform: -> String
    def self.revision: -> String
    def self.ticks: -> Integer
    def self.version: -> String
    def self.video_driver: -> String
    def self.screen_saver=: (untyped) -> void
    def self.screen_saver?: -> bool
    def self.video_drivers: -> [String?]
  end
end
