module SDLRuby
  module SDL
    # SDL_AUDIO_MASK_BITSIZE      = (0xFF)
    # SDL_AUDIO_MASK_DATATYPE     = (1<<8)
    # SDL_AUDIO_MASK_ENDIAN       = (1<<12)
    # SDL_AUDIO_MASK_SIGNED       = (1<<15)
    # SDL_AUDIO_BITSIZE(x)        = (x & SDL_AUDIO_MASK_BITSIZE)
    # SDL_AUDIO_ISFLOAT(x)        = (x & SDL_AUDIO_MASK_DATATYPE)
    # SDL_AUDIO_ISBIGENDIAN(x)    = (x & SDL_AUDIO_MASK_ENDIAN)
    # SDL_AUDIO_ISSIGNED(x)       = (x & SDL_AUDIO_MASK_SIGNED)
    # SDL_AUDIO_ISINT(x)          = (!SDL_AUDIO_ISFLOAT(x))
    # SDL_AUDIO_ISLITTLEENDIAN(x) = (!SDL_AUDIO_ISBIGENDIAN(x))
    # SDL_AUDIO_ISUNSIGNED(x)     = (!SDL_AUDIO_ISSIGNED(x))

    AUDIO_U8     = 0x0008
    AUDIO_S8     = 0x8008
    AUDIO_U16LSB = 0x0010
    AUDIO_S16LSB = 0x8010
    AUDIO_U16MSB = 0x1010
    AUDIO_S16MSB = 0x9010
    AUDIO_U16    = AUDIO_U16LSB
    AUDIO_S16    = AUDIO_S16LSB
    AUDIO_S32LSB = 0x8020
    AUDIO_S32MSB = 0x9020
    AUDIO_S32    = AUDIO_S32LSB
    AUDIO_F32LSB = 0x8120
    AUDIO_F32MSB = 0x9120
    AUDIO_F32    = AUDIO_F32LSB

    #if SDL_BYTEORDER == SDL_LIL_ENDIAN
    AUDIO_U16SYS = AUDIO_U16LSB
    AUDIO_S16SYS = AUDIO_S16LSB
    AUDIO_S32SYS = AUDIO_S32LSB
    AUDIO_F32SYS = AUDIO_F32LSB
    #else
    # AUDIO_U16SYS = AUDIO_U16MSB
    # AUDIO_S16SYS = AUDIO_S16MSB
    # AUDIO_S32SYS = AUDIO_S32MSB
    # AUDIO_F32SYS = AUDIO_F32MSB
    #endif

    SDL_AUDIO_ALLOW_FREQUENCY_CHANGE = 0x00000001
    SDL_AUDIO_ALLOW_FORMAT_CHANGE    = 0x00000002
    SDL_AUDIO_ALLOW_CHANNELS_CHANGE  = 0x00000004
    SDL_AUDIO_ALLOW_SAMPLES_CHANGE   = 0x00000008
    SDL_AUDIO_ALLOW_ANY_CHANGE       =
      SDL_AUDIO_ALLOW_FREQUENCY_CHANGE |
      SDL_AUDIO_ALLOW_FORMAT_CHANGE |
      SDL_AUDIO_ALLOW_CHANNELS_CHANGE |
      SDL_AUDIO_ALLOW_SAMPLES_CHANGE

    typealias "SDL_AudioCallback", "void*"

    SDL_AudioSpec = struct(
      [
        "int freq",
        "SDL_AudioFormat format",
        "Uint8 channels",
        "Uint8 silence",
        "Uint16 samples",
        "Uint16 padding",
        "Uint32 size",
        "SDL_AudioCallback callback",
        "void *userdata"
      ]
    )

    SDL_AUDIO_STOPPED = 0
    SDL_AUDIO_PLAYING = 1
    SDL_AUDIO_PAUSED = 2
    typealias "SDL_AudioStatus", "int"

    SDL_MIX_MAXVOLUME = 128
  end
end
