module SDLRuby
  module SDL
    SDL_SYSTEM_CURSOR_ARROW     = 0
    SDL_SYSTEM_CURSOR_IBEAM     = 1
    SDL_SYSTEM_CURSOR_WAIT      = 2
    SDL_SYSTEM_CURSOR_CROSSHAIR = 3
    SDL_SYSTEM_CURSOR_WAITARROW = 4
    SDL_SYSTEM_CURSOR_SIZENWSE  = 5
    SDL_SYSTEM_CURSOR_SIZENESW  = 6
    SDL_SYSTEM_CURSOR_SIZEWE    = 7
    SDL_SYSTEM_CURSOR_SIZENS    = 8
    SDL_SYSTEM_CURSOR_SIZEALL   = 9
    SDL_SYSTEM_CURSOR_NO        = 10
    SDL_SYSTEM_CURSOR_HAND      = 11
    SDL_NUM_SYSTEM_CURSORS      = 12

    SDL_MOUSEWHEEL_NORMAL = 0
    SDL_MOUSEWHEEL_FLIPPED = 1

    SDL_BUTTON = -> (x) { 1 << (x - 1) }
    SDL_BUTTON_LEFT   = 1
    SDL_BUTTON_MIDDLE = 2
    SDL_BUTTON_RIGHT  = 3
    SDL_BUTTON_X1     = 4
    SDL_BUTTON_X2     = 5
    SDL_BUTTON_LMASK  = SDL_BUTTON.(SDL_BUTTON_LEFT)
    SDL_BUTTON_MMASK  = SDL_BUTTON.(SDL_BUTTON_MIDDLE)
    SDL_BUTTON_RMASK  = SDL_BUTTON.(SDL_BUTTON_RIGHT)
    SDL_BUTTON_X1MASK = SDL_BUTTON.(SDL_BUTTON_X1)
    SDL_BUTTON_X2MASK = SDL_BUTTON.(SDL_BUTTON_X2)
  end
end
